hero_image: assets/img/hero3.jpg
hero_position: center center
# mobile_hero_image: assets/img/bell.jpg
# mobile_hero_position: center center

theme:
  # text_color: '#404040'
  primary_color: '#8FA598'
  secondary_color: '#8FA598'
  # accent_color: '#afa63d'
  # background_color: '#ffff'
