hero_image: assets/img/opg.jpg
hero_position: center center
# mobile_hero_image: assets/img/bell.jpg
# mobile_hero_position: center center

theme:
  # text_color: '#404040'
  primary_color: '#B2AC88'
  # secondary_color: '#a2a183'
  # accent_color: '#afa63d'
  # background_color: '#ffff'
